# Version 1.1

condense_wildcard_suffixes = true
force_multiline_blocks = true
format_macro_matchers = true
match_block_trailing_comma = true
merge_imports = true
normalize_comments = true
reorder_impl_items = true
struct_lit_single_line = false
tab_spaces = 2
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = false
